### PR TITLE
Implement global tracer support.

### PR DESCRIPTION
**Pull request by carlosalberto**
Initial support for a global tracer, based on the existing global tracer implementation for Java.

### CODE REVIEW

**Comment by carlosalberto** [comment]
Updated with a typo fix and added the recently added is_registered() function, as the Java API did.

**Comment by bhs** [comment]
@carlosalberto there is a (world-writeable) `tracer` *variable* in the `opentracing` module... we should stick with that xor move to something like this, but not both.

**Comment by carlosalberto** [comment]
Hey Ben, thanks for the feedback.

I had been thinking too lately about the in-place `opentracing.tracer` and how it would co-exist with the global tracer implementation. 

The more I think of it, the more I think we could keep it like this:

1) `opentracing.tracer` return the (new) global tracer's underneath tracer (alternatively, return it through a new `opentracing.get_tracer()` function)
2) For setting this global tracer, instead of setting it directly, have `opentracing.set_tracer()` - we need to have a method in order to lock the global tracer singleton, in case there's more than one thread trying to set it (which is what the Global Tracer Java implementation does).

Let me know what you think of this approach :)

**Comment by carlosalberto** [comment]
Oh - and a new `opentracing.is_tracer_registered()` function too, to let our users know whether or not there's already, uh,  a registered tracer ;)

**Comment by palazzem** [comment]
@carlosalberto this is an old PR, but since it's something we should take in consideration when migrating our Python implementation to OpenTracing, what's the plan here? What I see is:
* we can keep the `opentracing.tracer` like it is right now that as a default has the noop implementation and you simply set that one (error prone in my opinion since people may import `tracer` directly from their modules keeping the previous copy)
* provide something like Java where we have a global getter / setter

I'd say that one should replace the other (until there is a reason I'm missing right now) otherwise it will be confusing. In both cases, I suggest to keep the implementation simple. We may discuss about a couple of implementations if you're interested.

**Comment by carlosalberto** [comment]
Closing this PR, and will issue a new one after he have `Span` propagation in place.

**Pull request closed without merging**
