### PR TITLE
Rename opentracing.ext.scope_manager to opentracing.ext.scope_managers

### PR DESCRIPTION
**Pull request by carlosalberto**
As suggested by @palazzem 

Rational is that this submodule include more than one `ScopeManager` implementation, and thus it would be better to use a plural, `scope_managers`.

cc @yurishkuro @pglombardo

### CODE REVIEW

**Comment by yurishkuro** [comment]
hey, while on it, why even `ext`?

Side note - I always wanted to move tags from `ext` to `tags`.

**Comment by carlosalberto** [comment]
@yurishkuro Now it's probably a good time to move it to `opentracing.scope_managers` if you think that is better ;) 

Should I update such? I personally don't have a preference, honestly ;)

**Comment by palazzem** [comment]
Good point @yurishkuro . Totally agree to move it to `opentracing.scope_managers`.

**Comment by carlosalberto** [comment]
Updated. Check it out @palazzem @yurishkuro

**Comment by palazzem** [comment]
Good to go!

**Pull request merged**
