### PR TITLE
Use current_task from asyncio module for Python 3.9 compatibility

### PR DESCRIPTION
**Pull request by michael-leanix**
Python 3.7 deprecated using the class method `current_task` from asyncio.tasks.Task in favor of the same function in the asyncio.tasks module. With Python 3.9, the function is removed from asyncio.tasks.Task (which makes opentracing fail).
Not sure if this is the only issue with Python 3.9, but at least it's the only one I encountered so far.

### CODE REVIEW

**Review by hatala91 — COMMENTED** [review]
This is a great effort, thanks! Unfortunate, for the CI failing - if you fix that I'm happy to approve!

**Review by hatala91 — APPROVED** [review]
LGTM 🚀

**Comment by yurishkuro** [comment]
migrated repo to travis-ci.com, kicked off a build from master https://travis-ci.com/github/opentracing/opentracing-python/builds/202436733

**Comment by yurishkuro** [comment]
Master build also failed on 3.5, probably package incompatibility, I would suggest removing that version from the build matrix.

**Comment by michael-leanix** [comment]
Thanks a lot for the quick responses! Removing 3.5 seems reasonable as it's end of life anyway. Travis CI is green now 👍

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
released as 2.4.0

**Pull request merged**
