### PR TITLE
Replace the eccentric "referee" terminology

### PR DESCRIPTION
**Pull request by bensigelman**

### CODE REVIEW

**Comment by bensigelman** [comment]
@yurishkuro LGTY? This is (obviously) part of an effort to make terminology consistent across the board.

**Comment by bensigelman** [comment]
(btw, the test failures seem related to some sort of flake8 internal dependency... `make test lint` passes locally)

**Comment by yurishkuro** [comment]
LGTM

@bensigelman `make lint` fails locally as well if you reinstall virtualenv and rerun `make bootstrap`.  See [this fix](https://github.com/uber-common/opentracing-python-instrumentation/commit/9d4a61453c77bf0be2925fa6db3f6c0961350d19).

**Comment by bensigelman** [comment]
@yurishkuro thank you for the flake8 pointer!

**Pull request merged**
