### PR TITLE
No as such documentaion

### PR DESCRIPTION
**Pull request by Shreya1771**
There is no as such documentation written under the given directory. @JStickler please review :)

### CODE REVIEW

**Comment by JStickler** [comment]
@Shreya1771 , there is an initiative underway right now to change the documentation tools and structure for this project.

**Comment by shailesh** [comment]
Ok got it @JStickler 👍

**Comment by Shreya1771** [comment]
Ok got it @JStickler 👍

**Comment by yurishkuro** [comment]
I think the README is accurate, for now - when you run the code the docs are indeed generated under `docs/_build/html/index.html`.

**Pull request closed without merging**
